import 'package:flutter/material.dart';

enum AppLanguage { vi, en }

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  AppLanguage _currentLanguage = AppLanguage.vi;
  AppLanguage get currentLanguage => _currentLanguage;

  void setLanguage(AppLanguage lang) {
    _currentLanguage = lang;
    notifyListeners();
  }

  String t(String key) {
    final Map<String, String>? currentDict = translations[_currentLanguage];
    if (currentDict == null || !currentDict.containsKey(key)) {
      debugPrint('MISSING TRANSLATION KEY: $key for language: $_currentLanguage');
      return key;
    }
    return currentDict[key]!;
  }

  static const Map<AppLanguage, Map<String, String>> translations = {
    AppLanguage.vi: {
      'game_title': 'MA SÓI',
      'play': 'CHƠI',
      'role_library': 'THƯ VIỆN VAI TRÒ',
      'achievements': 'NHẬT KÝ & THÀNH TỰU',
      'settings': 'CÀI ĐẶT',
      'free_gold': 'Vàng miễn phí!',
      'choose_mode': 'CHỌN CHẾ ĐỘ CHƠI',
      'quick_match': 'GHÉP NHANH',
      'create_room': 'TẠO PHÒNG MỚI',
      'join_room': 'VÀO PHÒNG CÓ SẴN',
      'developing': 'Tính năng hiện đang phát triển!',
      'select_lang': 'CHỌN NGÔN NGỮ',
      'lang_vi': 'Tiếng Việt',
      'lang_en': 'English',
      'cancel': 'HỦY',
      'join': 'VÀO',
      'room_code_hint': 'Nhập mã phòng (VD: WS-XXXXXX)',
      'room_not_found': 'Phòng không tồn tại hoặc đã đóng!',
      'room_started': 'Phòng này đã bắt đầu trận đấu rồi!',
      'setup_room': 'THIẾT LẬP PHÒNG',
      'your_name': 'TÊN CỦA BẠN:',
      'player_count': 'Số người chơi:',
      'players': 'Người',
      'create_now': 'TẠO PHÒNG NGAY',
      'lobby_title': 'PHÒNG CHỜ ONLINE',
      'room_code_label': 'MÃ PHÒNG:',
      'waiting_players': 'Đang chờ người chơi...',
      'room_full': 'Phòng đã đầy!',
      'start_game': 'BẮT ĐẦU TRẬN ĐẤU',
      'waiting_host': 'CHỜ CHỦ PHÒNG...',
      'ready': 'SẴN SÀNG',
      'host': 'Host',
      'role_reveal_title': 'VAI TRÒ CỦA BẠN LÀ',
      'preparing_night': 'CHUẨN BỊ VÀO ĐÊM...',
      'night_phase': 'BAN ĐÊM',
      'day_phase': 'THẢO LUẬN',
      'voting_phase': 'BỎ PHIẾU',
      'night_number': 'ĐÊM',
      'day_number': 'NGÀY',
      'alive_count': 'SỐNG',
      'died_label': 'TỬ NẠN',
      'you_died': 'Bạn đã tử nạn.',
      'exit_room': 'RỜI PHÒNG',
      'back_to_menu': 'QUAY VỀ MENU CHÍNH',
      'victory': 'CHIẾN THẮNG!',
      'defeat': 'THẤT BẠI!',
      'chat_tab': 'TRÒ CHUYỆN 💬',
      'log_tab': 'NHẬT KÝ 📜',
      'chat_hint': 'Nhập tin nhắn...',
      'chat_night_disabled': 'Ban đêm không thể nói chuyện.',
      'chat_wolf_hint': 'Chat Bầy Sói...',
      'chat_ghost_hint': 'Kênh Hồn Ma...',
      'system': 'Hệ thống',
      'lobby_created': 'Tạo phòng thành công. Đang chờ người chơi...',
      'joined_room': 'Bạn đã tham gia phòng %s.',
      'match_started': 'Trận đấu bắt đầu!',
      'quick_match_started': 'Trận đấu ghép nhanh bắt đầu!',
      'night_start': 'bắt đầu.',
      'sunrise': 'Bình minh đã lên! Thảo luận (60s).',
      'voting_start': 'Bắt đầu bỏ phiếu (15s)!',
      'no_lynch': 'Không ai bị treo cổ.',
      'lynched': 'bị treo cổ!',
      'night_casualty': 'Đêm qua, %s đã bị Ma Sói cắn chết! 🩸',
      'poison_casualty': 'Đêm qua, Phù Thủy đã độc chết %s! 🧪',
      'seer_result': '%s là Phe %s',
      'guard_log': 'Bảo Vệ: Bạn đã bảo vệ %s.',
      'witch_save_log': 'Phù Thủy: Bạn đã cứu %s khỏi nanh vuốt Sói.',
      'witch_revive_log': 'Phù Thủy: Bạn đã hồi sinh %s từ cõi chết! ✨',
      'witch_poison_log': 'Phù Thủy: Bạn đã độc chết %s.',
      'curse_log': 'Sói Nguyền: Đã nguyền rủa %s.',
      'cupid_log': 'Cupid: Kết đôi %s & %s! ❤️',
      'gunner_log': 'Xạ Thủ: Đã nổ súng bắn chết %s!',
      'hunter_log': 'Thợ Săn: Đã bắn chết %s!',
      'lover_tragedy': 'Tình nhân hy sinh! 💔',
      'hunter_took_down': 'Thợ Săn kéo theo 1 người!',
      'bot_calm_down': 'Bình tĩnh nha ae.',
      'wolf_chat_open': 'Kênh chat Bầy Sói đã mở.',
      'wolf_red': 'SÓI 🔴',
      'villager_green': 'DÂN 🟢',
      'help_title': 'CẨM NANG SINH TỒN',
      'help_intro_title': 'KHỞI ĐẦU',
      'help_intro_content': 'Chào mừng đến với làng Ravenwood – nơi bóng tối rình rập và lòng tin là thứ xa xỉ nhất. Ma Sói không chỉ là một trò chơi, đó là cuộc đấu trí sinh tử giữa Ánh sáng và Bóng đêm.',
      'help_mechanic_title': 'LUẬT CHƠI CƠ BẢN',
      'help_mechanic_content': '• BAN ĐÊM: Bầy Sói thức giấc và chọn một con mồi. Các chức năng đặc biệt sẽ thực hiện nhiệm vụ thầm lặng của mình.\n• BAN NGÀY: Cả làng thức giấc, thảo luận về những gì đã xảy ra và bỏ phiếu treo cổ kẻ nghi ngờ là Sói.\n• MỤC TIÊU: Phe Dân thắng khi tiêu diệt hết Sói. Phe Sói thắng khi số lượng Sói bằng số dân làng còn sống.',
      'help_roles_title': 'DANH SÁCH VAI TRÒ',
      'action_wolf_bite': 'CẮN TIÊU DIỆT',
      'action_cancel_bite': 'HỦY CẮN',
      'action_seer_scan': 'SOI BÀI',
      'action_guard_protect': 'BẢO VỆ',
      'action_cancel_guard': 'HỦY BẢO VỆ',
      'action_witch_save': 'CỨU',
      'action_witch_poison': 'ĐỘC',
      'action_witch_revive': 'CỨU SỐNG',
      'action_witch_kill': 'DÙNG ĐỘC',
      'action_cancel_witch': 'HỦY SỬ DỤNG',
      'action_hunter_shot': 'BẮN KÉO THEO',
      'action_gunner_shoot': 'BẮN',
      'action_curse': 'NGUYỀN RỦA',
      'action_cancel_curse': 'HỦY NGUYỀN',
      'action_cupid_link': 'GHÉP ĐÔI ❤️',
      'action_unselect': 'BỎ CHỌN',
      'instruction_hunter': 'CHỌN 1 NGƯỜI VÀ BẤM [BẮN KÉO THEO]!',
      'instruction_cupid': 'Chọn 2 người để Ghép đôi.',
      'instruction_skill': 'Thực hiện kỹ năng của bạn...',
      'instruction_discuss': 'Thảo luận sôi nổi (60s).',
      'instruction_vote': 'Chạm người chơi để vote.',
      'instruction_target': 'Mục tiêu:',
      'role_dan': 'Dân Làng',
      'role_dan_desc': 'Tìm và bỏ phiếu treo cổ Ma Sói vào ban ngày.',
      'role_soi': 'Ma Sói',
      'role_soi_desc': 'Cùng bầy đàn tiêu diệt dân làng vào ban đêm.',
      'role_soi_nguyen': 'Sói Nguyền',
      'role_soi_nguyen_desc': 'Nguyền rủa khiến Tiên Tri soi sai phe mục tiêu.',
      'role_soi_dau_dan': 'Sói Đầu Đàn',
      'role_soi_dau_dan_desc': 'Lá phiếu cắn người ban đêm có giá trị gấp đôi.',
      'role_xa_thu': 'Xạ Thủ',
      'role_xa_thu_desc': 'Sở hữu 2 viên đạn để bắn hạ mục tiêu ban ngày.',
      'role_tien_tri': 'Tiên Tri',
      'role_tien_tri_desc': 'Mỗi đêm soi 1 người để biết phe của họ.',
      'role_cupid': 'Cupid',
      'role_cupid_desc': 'Ghép đôi 2 người, thắng khi cả hai sống sót.',
      'role_tho_san': 'Thợ Săn',
      'role_tho_san_desc': 'Bắn hạ 1 người chơi khác nếu bạn tử nạn.',
      'role_bao_ve': 'Bảo Vệ',
      'role_bao_ve_desc': 'Mỗi đêm chọn bảo vệ 1 người khỏi Ma Sói.',
      'role_phu_thuy': 'Phù Thủy',
      'role_phu_thuy_desc': 'Có 1 bình thuốc cứu sống và 1 bình thuốc độc, chỉ sử dụng vào ban đêm.',
      'role_nerd': 'Kẻ Ngốc',
      'role_nerd_desc': 'Giành chiến thắng nếu bị dân làng treo cổ.',
      'tip_dan_1': 'Hãy quan sát kỹ thái độ của những người chơi khác.',
      'tip_dan_2': 'Đừng quá im lặng, bạn sẽ dễ bị nghi ngờ là Sói.',
      'tip_soi_1': 'Hãy phối hợp cùng bầy sói để tiêu diệt các chức năng quan trọng.',
      'tip_soi_2': 'Tự tin giả làm dân làng hoặc một chức năng khác để ẩn thân.',
      'tip_soi_nguyen_1': 'Nguyền rủa người chơi có khả năng cao là Tiên Tri để gây nhiễu loạn thông tin.',
      'tip_soi_dau_dan_1': 'Lá phiếu của bạn rất quan trọng, hãy thảo luận kỹ với bầy sói trước khi quyết định mục tiêu.',
      'tip_xa_thu_1': 'Hãy giữ đạn cho đến khi bạn thực sự chắc chắn về mục tiêu, vì bạn sẽ lộ diện sau phát bắn đầu tiên.',
      'tip_tien_tri_1': 'Cố gắng sống sót càng lâu càng tốt để thu thập thêm thông tin.',
      'tip_tien_tri_2': 'Đừng vội vàng lộ diện, hãy khéo léo đưa ra gợi ý cho dân làng.',
      'tip_cupid_1': 'Ghép đôi hai người bạn tin tưởng để tạo ra một phe thứ ba mạnh mẽ.',
      'tip_tho_san_1': 'Nếu bạn bị cắn, hãy nhắm vào người mà bạn nghi ngờ nhất là Sói.',
      'tip_bao_ve_1': 'Phán đoán mục tiêu tiếp theo của Sói để bảo vệ kịp thời.',
      'tip_bao_ve_2': 'Đừng quên rằng bạn không thể bảo vệ cùng một người trong hai đêm liên tiếp.',
      'tip_phu_thuy_1': 'Sử dụng bình cứu cho các chức năng quan trọng như Tiên Tri hoặc Bảo Vệ.',
      'tip_phu_thuy_2': 'Bình độc là vũ khí nguy hiểm, hãy cẩn trọng kẻo giết nhầm dân làng.',
      'tip_nerd_1': 'Hãy cư xử một cách đáng nghi nhưng đừng quá lộ liễu để dân làng treo cổ bạn.',
      'role_dan_lore': 'Sinh ra và lớn lên giữa những cánh rừng già Ravenwood, họ là những con người hiền lành nhưng kiên cường, luôn giữ vững niềm tin vào ánh sáng ngay cả khi bóng tối bủa vây từng ngôi nhà.',
      'role_soi_lore': 'Mang trong mình dòng máu quỷ dữ của mặt trăng máu. Khi đêm xuống, phần người biến mất, chỉ còn lại bản năng săn mồi tàn độc và tiếng hú xé toạc màn đêm lạnh lẽo.',
      'role_soi_nguyen_lore': 'Từng là một kẻ sùng đạo bị trục xuất, hắn giờ đây dùng tà thuật cổ xưa để vấy bẩn linh hồn người khác, khiến những kẻ trong sạch nhất cũng trở nên u tối trong mắt đấng tiên tri.',
      'role_soi_dau_dan_lore': 'Vị thủ lĩnh uy nghiêm với uy quyền tuyệt đối trong bầy đàn. Tiếng hú của hắn không chỉ là mệnh lệnh tấn công, mà còn là nỗi khiếp sợ gieo rắc sâu vào tâm khảm kẻ thù.',
      'role_xa_thu_lore': 'Với đôi tay chưa bao giờ run và tầm ngắm chính xác tuyệt đối, anh là niềm hy vọng cuối cùng của dân làng để thực thi công lý ngay giữa ánh mặt trời.',
      'role_tien_tri_lore': 'Người được ban tặng đôi mắt thấu thị, có thể nhìn xuyên thấu màn sương mờ của số phận. Nhưng sự thật thường đi kèm với cái giá là nỗi cô đơn và gánh nặng của kẻ biết trước tương lai.',
      'role_cupid_lore': 'Vị thần tình yêu tinh quái, người tìm thấy niềm vui trong việc thắt chặt những sợi dây tơ hồng định mệnh, bất chấp việc chúng có thể trở thành thòng lọng tử thần cho cả hai.',
      'role_tho_san_lore': 'Gã thợ săn già thiện chiến, người luôn sống với tôn chỉ: nếu hơi thở này phải trút xuống, thì kẻ thù cũng không bao giờ được phép sống sót để nhìn thấy bình minh.',
      'role_bao_ve_lore': 'Hiệp sĩ thầm lặng của ngôi làng, người luôn thức trắng đêm bên những cánh cửa khép kín, sẵn sàng dùng tấm khiên và cả mạng sống để che chở cho đồng bào khỏi nanh vuốt quỷ dữ.',
      'role_phu_thuy_lore': 'Bậc thầy về thảo dược và độc dược, bà nắm giữ ranh giới mong manh giữa sự sống và cái chết trong lòng bàn tay. Một giọt thuốc có thể là phép màu, nhưng cũng có thể là sự chấm hết.',
      'role_nerd_lore': 'Một linh hồn lạc lối với tâm trí vỡ vụn, người tìm thấy sự giải thoát duy nhất trong tiếng cười nhạo báng của đám đông và cái chết vinh quang trên giá treo cổ.',
    },
    AppLanguage.en: {
      'game_title': 'WEREWOLF',
      'play': 'PLAY',
      'role_library': 'ROLE LIBRARY',
      'achievements': 'DIARY & ACHIEVEMENTS',
      'settings': 'SETTINGS',
      'free_gold': 'Free Gold!',
      'choose_mode': 'CHOOSE GAME MODE',
      'quick_match': 'QUICK MATCH',
      'create_room': 'CREATE NEW ROOM',
      'join_room': 'JOIN EXISTING ROOM',
      'developing': 'Feature currently under development!',
      'select_lang': 'SELECT LANGUAGE',
      'lang_vi': 'Vietnamese',
      'lang_en': 'English',
      'cancel': 'CANCEL',
      'join': 'JOIN',
      'room_code_hint': 'Enter room code (EX: WS-XXXXXX)',
      'room_not_found': 'Room does not exist or is closed!',
      'room_started': 'This room has already started!',
      'setup_room': 'SETUP ROOM',
      'your_name': 'YOUR NAME:',
      'player_count': 'Player count:',
      'players': 'Players',
      'create_now': 'CREATE ROOM NOW',
      'lobby_title': 'ONLINE LOBBY',
      'room_code_label': 'ROOM CODE:',
      'waiting_players': 'Waiting for players...',
      'room_full': 'Room is full!',
      'start_game': 'START MATCH',
      'waiting_host': 'WAITING FOR HOST...',
      'ready': 'READY',
      'host': 'Host',
      'role_reveal_title': 'YOUR ROLE IS',
      'preparing_night': 'PREPARING FOR NIGHT...',
      'night_phase': 'NIGHT PHASE',
      'day_phase': 'DISCUSSION',
      'voting_phase': 'VOTING',
      'night_number': 'NIGHT',
      'day_number': 'DAY',
      'alive_count': 'ALIVE',
      'died_label': 'DIED',
      'you_died': 'You are dead.',
      'exit_room': 'EXIT ROOM',
      'back_to_menu': 'BACK TO MAIN MENU',
      'victory': 'VICTORY!',
      'defeat': 'DEFEAT!',
      'chat_tab': 'CHAT 💬',
      'log_tab': 'LOGS 📜',
      'chat_hint': 'Type a message...',
      'chat_night_disabled': 'Cannot talk at night.',
      'chat_wolf_hint': 'Werewolf Chat...',
      'chat_ghost_hint': 'Ghost Channel...',
      'system': 'System',
      'lobby_created': 'Lobby created. Waiting for players...',
      'joined_room': 'Joined room %s.',
      'match_started': 'Match started!',
      'quick_match_started': 'Quick match started!',
      'night_start': 'starts.',
      'sunrise': 'Sunrise! Discussion (60s).',
      'voting_start': 'Voting starts (15s)!',
      'no_lynch': 'No one was hanged.',
      'lynched': 'was hanged!',
      'night_casualty': 'Last night, %s was killed by Werewolves! 🩸',
      'poison_casualty': 'Last night, the Witch poisoned %s! 🧪',
      'seer_result': '%s is Team %s',
      'guard_log': 'Bodyguard: You protected %s.',
      'witch_save_log': 'Witch: You saved %s from Wolves.',
      'witch_revive_log': 'Witch: You revived %s from the dead! ✨',
      'witch_poison_log': 'Witch: You poisoned %s.',
      'curse_log': 'Cursed Wolf: Cursed %s.',
      'cupid_log': 'Cupid: Linked %s & %s! ❤️',
      'gunner_log': 'Gunner: Shot and killed %s!',
      'hunter_log': 'Hunter: Shot and killed %s!',
      'lover_tragedy': 'Lovers tragedy! 💔',
      'hunter_took_down': 'Hunter took someone down!',
      'bot_calm_down': 'Calm down guys.',
      'wolf_chat_open': 'Werewolf chat channel opened.',
      'wolf_red': 'WOLF 🔴',
      'villager_green': 'VILLAGER 🟢',
      'action_wolf_bite': 'BITE TO KILL',
      'action_cancel_bite': 'CANCEL BITE',
      'action_seer_scan': 'SCAN',
      'action_guard_protect': 'PROTECT',
      'action_cancel_guard': 'CANCEL PROTECT',
      'action_witch_save': 'SAVE',
      'action_witch_poison': 'POISON',
      'action_witch_revive': 'REVIVE',
      'action_witch_kill': 'USE POISON',
      'action_cancel_witch': 'CANCEL USE',
      'action_hunter_shot': 'SHOOT ALONG',
      'action_gunner_shoot': 'SHOOT',
      'action_curse': 'CURSE',
      'action_cancel_curse': 'CANCEL CURSE',
      'action_cupid_link': 'LINK ❤️',
      'action_unselect': 'UNSELECT',
      'instruction_hunter': 'SELECT 1 PERSON AND PRESS [SHOOT ALONG]!',
      'instruction_cupid': 'Select 2 people to Link.',
      'instruction_skill': 'Use your skill...',
      'instruction_discuss': 'Discussion phase (60s).',
      'instruction_vote': 'Tap player to vote.',
      'instruction_target': 'Target:',
      'role_dan': 'Villager',
      'role_dan_desc': 'Find and vote to lynch Werewolves during the day.',
      'role_soi': 'Werewolf',
      'role_soi_desc': 'Eliminate villagers at night with your pack.',
      'role_soi_nguyen': 'Cursed Wolf',
      'role_soi_nguyen_desc': 'Curse a player to make the Seer see them as a Wolf.',
      'role_soi_dau_dan': 'Alpha Wolf',
      'role_soi_dau_dan_desc': 'Your night bite vote counts as double.',
      'role_xa_thu': 'Gunner',
      'role_xa_thu_desc': 'Has 2 bullets to shoot down suspects during the day.',
      'role_tien_tri': 'Seer',
      'role_tien_tri_desc': 'Scan 1 player each night to reveal their team.',
      'role_cupid': 'Cupid',
      'role_cupid_desc': 'Link 2 players; win if both survive until the end.',
      'role_tho_san': 'Hunter',
      'role_tho_san_desc': 'Take someone down with you if you are eliminated.',
      'role_bao_ve': 'Bodyguard',
      'role_bao_ve_desc': 'Protect 1 person from Werewolves each night.',
      'role_phu_thuy': 'Witch',
      'role_phu_thuy_desc': 'Has one saving potion and one poison potion.',
      'role_nerd': 'The Nerd',
      'role_nerd_desc': 'Wins if successfully voted to be hanged by the village.',
      'tip_dan_1': 'Observe other players\' attitudes carefully.',
      'tip_dan_2': 'Don\'t be too quiet, you\'ll be easily suspected as a Wolf.',
      'tip_soi_1': 'Coordinate with the pack to eliminate key roles.',
      'tip_soi_2': 'Confidently pretend to be a villager or another role to hide.',
      'tip_soi_nguyen_1': 'Curse players who are likely the Seer to disrupt information.',
      'tip_soi_dau_dan_1': 'Your vote is crucial, discuss carefully with the pack before deciding.',
      'tip_xa_thu_1': 'Hold your fire until you are sure, as you reveal yourself after the first shot.',
      'tip_tien_tri_1': 'Try to survive as long as possible to gather more info.',
      'tip_tien_tri_2': 'Don\'t reveal yourself too early, give subtle hints to the village.',
      'tip_cupid_1': 'Link two people you trust to create a strong third faction.',
      'tip_tho_san_1': 'If you are bitten, aim for the person you suspect most as a Wolf.',
      'tip_bao_ve_1': 'Predict the Wolves\' next target to protect in time.',
      'tip_bao_ve_2': 'Remember, you cannot protect the same person two nights in a row.',
      'tip_phu_thuy_1': 'Use the heal potion on key roles like Seer or Bodyguard.',
      'tip_phu_thuy_2': 'The poison potion is a dangerous weapon, be careful not to kill a villager.',
      'tip_nerd_1': 'Behave suspiciously but not too obviously so the village hangs you.',
      'role_dan_lore': 'Born and raised in the ancient forests of Ravenwood, they are gentle yet resilient people who hold fast to their faith in the light even as darkness surrounds their homes.',
      'role_soi_lore': 'Stained by the curse of the Blood Moon. When night falls, their humanity vanishes, leaving only a brutal predatory instinct and a howl that pierces the freezing night air.',
      'role_soi_nguyen_lore': 'Once a devout believer but now an outcast, he uses ancient dark magic to taint the souls of others, making even the purest hearts appear dark in the eyes of the Prophet.',
      'role_soi_dau_dan_lore': 'A majestic leader with absolute authority over the pack. His howl is not just a call to attack, but a wave of terror sowed deep within the hearts of his enemies.',
      'role_xa_thu_lore': 'With hands that never tremble and a gaze of absolute precision, he is the last hope of the villagers to enforce justice right under the high sun.',
      'role_tien_tri_lore': 'Gifted with clairvoyant eyes that pierce through the fog of fate. But the truth often comes with the price of extreme solitude and the burden of knowing the future.',
      'role_cupid_lore': 'The mischievous god of love who finds joy in tying the red strings of destiny, regardless of whether they might become a death noose for both.',
      'role_tho_san_lore': 'A battle-hardened old hunter who lives by one rule: if this breath must fade, the enemy shall never be allowed to live to see the dawn.',
      'role_bao_ve_lore': 'The silent knight of the village, who stays awake through the night behind closed doors, ready to use his shield and his life to protect his kin from the demons\' claws.',
      'role_phu_thuy_lore': 'A master of herbs and poisons, she holds the thin line between life and death in her hands. One drop can be a miracle, but another can be the end.',
      'role_nerd_lore': 'A lost soul with a shattered mind, finding his only release in the mocking laughter of the crowd and a glorious death upon the gallows.',
    }
  };
}

final langSvc = LanguageService(); // Global instance
