import 'package:flutter/material.dart';

enum AppLanguage { vi, en }

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  AppLanguage _currentLanguage = AppLanguage.vi;
  AppLanguage get currentLanguage => _currentLanguage;

  void setLanguage(AppLanguage lang) {
    _currentLanguage = lang;
    notifyListeners();
  }

  String t(String key) {
    final Map<String, String>? currentDict = translations[_currentLanguage];
    if (currentDict == null || !currentDict.containsKey(key)) {
      debugPrint('MISSING TRANSLATION KEY: $key for language: $_currentLanguage');
      return key;
    }
    return currentDict[key]!;
  }

  static const Map<AppLanguage, Map<String, String>> translations = {
    AppLanguage.vi: {
      'game_title': 'MA SÓI',
      'play': 'CHƠI',
      'inventory': 'TÚI ĐỒ',
      'profile': 'HỒ SƠ',
      'settings': 'CÀI ĐẶT',
      'free_gold': 'Vàng miễn phí!',
      'choose_mode': 'CHỌN CHẾ ĐỘ CHƠI',
      'quick_match': 'GHÉP NHANH',
      'create_room': 'TẠO PHÒNG MỚI',
      'join_room': 'VÀO PHÒNG CÓ SẴN',
      'developing': 'Tính năng hiện đang phát triển!',
      'select_lang': 'CHỌN NGÔN NGỮ',
      'lang_vi': 'Tiếng Việt',
      'lang_en': 'English',
      'cancel': 'HỦY',
      'join': 'VÀO',
      'room_code_hint': 'Nhập mã phòng (VD: WS-XXXXXX)',
      'room_not_found': 'Phòng không tồn tại hoặc đã đóng!',
      'room_started': 'Phòng này đã bắt đầu trận đấu rồi!',
      'setup_room': 'THIẾT LẬP PHÒNG',
      'your_name': 'TÊN CỦA BẠN:',
      'player_count': 'Số lượng người chơi:',
      'players': 'Người',
      'create_now': 'TẠO PHÒNG NGAY',
      'lobby_title': 'PHÒNG CHỜ ONLINE',
      'room_code_label': 'MÃ PHÒNG:',
      'waiting_players': 'Đang chờ người chơi...',
      'room_full': 'Phòng đã đầy!',
      'start_game': 'BẮT ĐẦU TRẬN ĐẤU',
      'waiting_host': 'CHỜ CHỦ PHÒNG...',
      'ready': 'SẴN SÀNG',
      'host': 'Host',
      'role_reveal_title': 'VAI TRÒ CỦA BẠN LÀ',
      'preparing_night': 'CHUẨN BỊ VÀO ĐÊM...',
      'night_phase': 'BAN ĐÊM',
      'day_phase': 'THẢO LUẬN',
      'voting_phase': 'BỎ PHIẾU',
      'night_number': 'ĐÊM',
      'day_number': 'NGÀY',
      'alive_count': 'SỐNG',
      'died_label': 'TỬ NẠN',
      'you_died': 'Bạn đã tử nạn.',
      'exit_room': 'RỜI PHÒNG',
      'back_to_menu': 'QUAY VỀ MENU CHÍNH',
      'victory': 'CHIẾN THẮNG!',
      'defeat': 'THẤT BẠI!',
      'chat_tab': 'TRÒ CHUYỆN 💬',
      'log_tab': 'NHẬT KÝ 📜',
      'chat_hint': 'Nhập tin nhắn...',
      'chat_night_disabled': 'Ban đêm không thể nói chuyện.',
      'chat_wolf_hint': 'Chat Bầy Sói...',
      'chat_ghost_hint': 'Kênh Hồn Ma...',
      'system': 'Hệ thống',
      'lobby_created': 'Tạo phòng thành công. Đang chờ người chơi...',
      'joined_room': 'Bạn đã tham gia phòng',
      'match_started': 'Trận đấu bắt đầu!',
      'night_start': 'bắt đầu.',
      'sunrise': 'Bình minh đã lên! Thảo luận (60s).',
      'voting_start': 'Bắt đầu bỏ phiếu (15s)!',
      'no_lynch': 'Không ai bị treo cổ.',
      'lynched': 'bị treo cổ!',
      'night_casualty': 'Đêm qua, %s đã bị Ma Sói cắn chết! 🩸',
      'poison_casualty': 'Đêm qua, Phù Thủy đã độc chết %s! 🧪',
      'seer_result': '%s là Phe %s',
      'guard_log': 'Bảo Vệ: Bạn đã bảo vệ %s.',
      'witch_save_log': 'Phù Thủy: Bạn đã cứu %s khỏi nanh vuốt Sói.',
      'witch_revive_log': 'Phù Thủy: Bạn đã hồi sinh %s từ cõi chết! ✨',
      'witch_poison_log': 'Phù Thủy: Bạn đã độc chết %s.',
      'curse_log': 'Sói Nguyền: Đã nguyền rủa %s.',
      'cupid_log': 'Cupid: Kết đôi %s & %s! ❤️',
      'gunner_log': 'Xạ Thủ: Đã nổ súng bắn chết %s!',
      'hunter_log': 'Thợ Săn: Đã bắn chết %s!',
      'lover_tragedy': 'Tình nhân hy sinh! 💔',
      'hunter_took_down': 'Thợ Săn kéo theo 1 người!',
      'bot_calm_down': 'Bình tĩnh nha ae.',
      'wolf_chat_open': 'Kênh chat Bầy Sói đã mở.',
      'wolf_red': 'SÓI 🔴',
      'villager_green': 'DÂN 🟢',
      'help_title': 'HƯỚNG DẪN TRÒ CHƠI',
      'help_intro_title': 'GIỚI THIỆU',
      'help_intro_content': 'Ma Sói là trò chơi đấu trí giữa hai phe: Dân Làng và Ma Sói. Ban đêm, bầy Sói sẽ lén lút sát hại một người dân. Ban ngày, Dân Làng sẽ thảo luận và bỏ phiếu để treo cổ kẻ mà họ nghi ngờ là Sói.',
      'help_roles_title': 'VAI TRÒ TRONG GAME',
      'action_wolf_bite': 'CẮN TIÊU DIỆT',
      'action_cancel_bite': 'HỦY CẮN',
      'action_seer_scan': 'SOI BÀI',
      'action_guard_protect': 'BẢO VỆ',
      'action_cancel_guard': 'HỦY BẢO VỆ',
      'action_witch_save': 'CỨU',
      'action_witch_poison': 'ĐỘC',
      'action_witch_revive': 'CỨU SỐNG',
      'action_witch_kill': 'DÙNG ĐỘC',
      'action_cancel_witch': 'HỦY SỬ DỤNG',
      'action_hunter_shot': 'BẮN KÉO THEO',
      'action_gunner_shoot': 'BẮN',
      'action_curse': 'NGUYỀN RỦA',
      'action_cancel_curse': 'HỦY NGUYỀN',
      'action_cupid_link': 'GHÉP ĐÔI ❤️',
      'action_unselect': 'BỎ CHỌN',
      'instruction_hunter': 'CHỌN 1 NGƯỜI VÀ BẤM [BẮN KÉO THEO]!',
      'instruction_cupid': 'Chọn 2 người để Ghép đôi.',
      'instruction_skill': 'Thực hiện kỹ năng của bạn...',
      'instruction_discuss': 'Thảo luận sôi nổi (60s).',
      'instruction_vote': 'Chạm người chơi để vote.',
      'instruction_target': 'Mục tiêu:',
      'role_dan': 'Dân Làng',
      'role_dan_desc': 'Không có chức năng, bỏ phiếu tìm sói ban ngày.',
      'role_soi': 'Ma Sói',
      'role_soi_desc': 'Cắn người vào ban đêm cùng bầy sói.',
      'role_soi_nguyen': 'Sói Nguyền',
      'role_soi_nguyen_desc': 'Nguyền rủa người chơi ban ngày khiến Tiên Tri soi ra là Sói.',
      'role_soi_dau_dan': 'Sói Đầu Đàn',
      'role_soi_dau_dan_desc': 'Lá phiếu vote ban đêm có giá trị gấp đôi.',
      'role_xa_thu': 'Xạ Thủ',
      'role_xa_thu_desc': 'Có 2 viên đạn bắn ban ngày, bắn phát đầu sẽ lộ diện.',
      'role_tien_tri': 'Tiên Tri',
      'role_tien_tri_desc': 'Soi 1 người mỗi đêm để biết họ thuộc phe Dân hay Sói.',
      'role_cupid': 'Cupid',
      'role_cupid_desc': 'Ghép đôi 2 người, nếu 1 người chết người kia chết theo.',
      'role_tho_san': 'Thợ Săn',
      'role_tho_san_desc': 'Nếu chết có thể chọn nổ súng bắn kéo theo 1 người.',
      'role_bao_ve': 'Bảo Vệ',
      'role_bao_ve_desc': 'Bảo vệ 1 người mỗi đêm khỏi sói (không bảo vệ 1 người 2 đêm liên tiếp).',
      'role_phu_thuy': 'Phù Thủy',
      'role_phu_thuy_desc': 'Có 1 bình cứu (cứu người bị cắn hoặc hồi sinh) và 1 bình độc.',
      'role_nerd': 'Kẻ Ngốc',
      'role_nerd_desc': 'Thắng nếu bị dân làng treo cổ vào ban ngày.',
    },
    AppLanguage.en: {
      'game_title': 'WEREWOLF',
      'play': 'PLAY',
      'inventory': 'INVENTORY',
      'profile': 'PROFILE',
      'settings': 'SETTINGS',
      'free_gold': 'Free Gold!',
      'choose_mode': 'CHOOSE GAME MODE',
      'quick_match': 'QUICK MATCH',
      'create_room': 'CREATE NEW ROOM',
      'join_room': 'JOIN EXISTING ROOM',
      'developing': 'Feature currently under development!',
      'select_lang': 'SELECT LANGUAGE',
      'lang_vi': 'Vietnamese',
      'lang_en': 'English',
      'cancel': 'CANCEL',
      'join': 'JOIN',
      'room_code_hint': 'Enter room code (EX: WS-XXXXXX)',
      'room_not_found': 'Room does not exist or is closed!',
      'room_started': 'This room has already started!',
      'setup_room': 'SETUP ROOM',
      'your_name': 'YOUR NAME:',
      'player_count': 'Player count:',
      'players': 'Players',
      'create_now': 'CREATE ROOM NOW',
      'lobby_title': 'ONLINE LOBBY',
      'room_code_label': 'ROOM CODE:',
      'waiting_players': 'Waiting for players...',
      'room_full': 'Room is full!',
      'start_game': 'START MATCH',
      'waiting_host': 'WAITING FOR HOST...',
      'ready': 'READY',
      'host': 'Host',
      'role_reveal_title': 'YOUR ROLE IS',
      'preparing_night': 'PREPARING FOR NIGHT...',
      'night_phase': 'NIGHT PHASE',
      'day_phase': 'DISCUSSION',
      'voting_phase': 'VOTING',
      'night_number': 'NIGHT',
      'day_number': 'DAY',
      'alive_count': 'ALIVE',
      'died_label': 'DIED',
      'you_died': 'You are dead.',
      'exit_room': 'EXIT ROOM',
      'back_to_menu': 'BACK TO MAIN MENU',
      'victory': 'VICTORY!',
      'defeat': 'DEFEAT!',
      'chat_tab': 'CHAT 💬',
      'log_tab': 'LOGS 📜',
      'chat_hint': 'Type a message...',
      'chat_night_disabled': 'Cannot talk at night.',
      'chat_wolf_hint': 'Werewolf Chat...',
      'chat_ghost_hint': 'Ghost Channel...',
      'system': 'System',
      'lobby_created': 'Lobby created. Waiting for players...',
      'joined_room': 'Joined room',
      'match_started': 'Match started!',
      'night_start': 'starts.',
      'sunrise': 'Sunrise! Discussion (60s).',
      'voting_start': 'Voting starts (15s)!',
      'no_lynch': 'No one was hanged.',
      'lynched': 'was hanged!',
      'night_casualty': 'Last night, %s was killed by Werewolves! 🩸',
      'poison_casualty': 'Last night, the Witch poisoned %s! 🧪',
      'seer_result': '%s is Team %s',
      'guard_log': 'Bodyguard: You protected %s.',
      'witch_save_log': 'Witch: You saved %s from Wolves.',
      'witch_revive_log': 'Witch: You revived %s from the dead! ✨',
      'witch_poison_log': 'Witch: You poisoned %s.',
      'curse_log': 'Cursed Wolf: Cursed %s.',
      'cupid_log': 'Cupid: Linked %s & %s! ❤️',
      'gunner_log': 'Gunner: Shot and killed %s!',
      'hunter_log': 'Hunter: Shot and killed %s!',
      'lover_tragedy': 'Lovers tragedy! 💔',
      'hunter_took_down': 'Hunter took someone down!',
      'bot_calm_down': 'Calm down guys.',
      'wolf_chat_open': 'Werewolf chat channel opened.',
      'wolf_red': 'WOLF 🔴',
      'villager_green': 'VILLAGER 🟢',
      'action_wolf_bite': 'BITE TO KILL',
      'action_cancel_bite': 'CANCEL BITE',
      'action_seer_scan': 'SCAN',
      'action_guard_protect': 'PROTECT',
      'action_cancel_guard': 'CANCEL PROTECT',
      'action_witch_save': 'SAVE',
      'action_witch_poison': 'POISON',
      'action_witch_revive': 'REVIVE',
      'action_witch_kill': 'USE POISON',
      'action_cancel_witch': 'CANCEL USE',
      'action_hunter_shot': 'SHOOT ALONG',
      'action_gunner_shoot': 'SHOOT',
      'action_curse': 'CURSE',
      'action_cancel_curse': 'CANCEL CURSE',
      'action_cupid_link': 'LINK ❤️',
      'action_unselect': 'UNSELECT',
      'instruction_hunter': 'SELECT 1 PERSON AND PRESS [SHOOT ALONG]!',
      'instruction_cupid': 'Select 2 people to Link.',
      'instruction_skill': 'Use your skill...',
      'instruction_discuss': 'Discussion phase (60s).',
      'instruction_vote': 'Tap player to vote.',
      'instruction_target': 'Target:',
      'help_title': 'GAME GUIDE',
      'help_intro_title': 'INTRODUCTION',
      'help_intro_content': 'Werewolf is a game of wits between two teams: Villagers and Werewolves. At night, Werewolves secretly eliminate a villager. During the day, Villagers discuss and vote to hang who they suspect is a Wolf.',
      'help_roles_title': 'GAME ROLES',
      'role_dan': 'Villager',
      'role_dan_desc': 'No ability, vote to find wolves during the day.',
      'role_soi': 'Werewolf',
      'role_soi_desc': 'Kill someone at night with the pack.',
      'role_soi_nguyen': 'Cursed Wolf',
      'role_soi_nguyen_desc': 'Curse someone during the day so Seer sees them as a Wolf.',
      'role_soi_dau_dan': 'Alpha Wolf',
      'role_soi_dau_dan_desc': 'Night vote counts as double.',
      'role_xa_thu': 'Gunner',
      'role_xa_thu_desc': 'Has 2 bullets to shoot during the day, first shot reveals role.',
      'role_tien_tri': 'Seer',
      'role_tien_tri_desc': 'Scan 1 player each night to know their team (Villager or Wolf).',
      'role_cupid': 'Cupid',
      'role_cupid_desc': 'Link 2 players, if one dies, the other follows.',
      'role_tho_san': 'Hunter',
      'role_tho_san_desc': 'If you die, take someone with you.',
      'role_bao_ve': 'Bodyguard',
      'role_bao_ve_desc': 'Protect 1 person each night from wolves (cannot protect twice).',
      'role_phu_thuy': 'Witch',
      'role_phu_thuy_desc': 'Has 1 saving potion (save/revive) and 1 poison potion.',
      'role_nerd': 'The Nerd',
      'role_nerd_desc': 'Wins if hanged by the village during the day.',
    }
  };
}

final langSvc = LanguageService(); // Global instance
