// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8l4lZoRUqvMw-84qGTXO_D5kzE9uWg2E',
    appId: '1:801531000584:web:61ff18245cc5169dde1ebd',
    messagingSenderId: '801531000584',
    projectId: 'werewolf-prm-v2',
    authDomain: 'werewolf-prm-v2.firebaseapp.com',
    storageBucket: 'werewolf-prm-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWRsUTiAPmeo2cV3V0AwPRGah85QxfZc0',
    appId: '1:801531000584:android:ce0efecab6a11da3de1ebd',
    messagingSenderId: '801531000584',
    projectId: 'werewolf-prm-v2',
    storageBucket: 'werewolf-prm-v2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlZSZp1T7SFt9xQlNXaTwXpjbDpytKh_s',
    appId: '1:801531000584:ios:e427626e84984995de1ebd',
    messagingSenderId: '801531000584',
    projectId: 'werewolf-prm-v2',
    storageBucket: 'werewolf-prm-v2.firebasestorage.app',
    iosBundleId: 'com.example.werewolf',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlZSZp1T7SFt9xQlNXaTwXpjbDpytKh_s',
    appId: '1:801531000584:ios:e427626e84984995de1ebd',
    messagingSenderId: '801531000584',
    projectId: 'werewolf-prm-v2',
    storageBucket: 'werewolf-prm-v2.firebasestorage.app',
    iosBundleId: 'com.example.werewolf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8l4lZoRUqvMw-84qGTXO_D5kzE9uWg2E',
    appId: '1:801531000584:web:b7fc7917bc0ec644de1ebd',
    messagingSenderId: '801531000584',
    projectId: 'werewolf-prm-v2',
    authDomain: 'werewolf-prm-v2.firebaseapp.com',
    storageBucket: 'werewolf-prm-v2.firebasestorage.app',
  );
}
