// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA004ZSMMQgZBwpYrWJtID-GJTXL1tcC4A',
    appId: '1:144006347482:web:286a32a4c54f3a023283e3',
    messagingSenderId: '144006347482',
    projectId: 'werewolf-prm-7717c',
    authDomain: 'werewolf-prm-7717c.firebaseapp.com',
    databaseURL: 'https://werewolf-prm-7717c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'werewolf-prm-7717c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU9qvs6DiUpzrJCAuDAFab3RMp-XaAEd0',
    appId: '1:144006347482:android:8d64c4e090c8e77c3283e3',
    messagingSenderId: '144006347482',
    projectId: 'werewolf-prm-7717c',
    databaseURL: 'https://werewolf-prm-7717c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'werewolf-prm-7717c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd8O83n4JGhUqCJdxOqwLZIkPeYl_6Fx0',
    appId: '1:144006347482:ios:1477b85f6c0caed53283e3',
    messagingSenderId: '144006347482',
    projectId: 'werewolf-prm-7717c',
    databaseURL: 'https://werewolf-prm-7717c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'werewolf-prm-7717c.firebasestorage.app',
    iosBundleId: 'com.example.werewolf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd8O83n4JGhUqCJdxOqwLZIkPeYl_6Fx0',
    appId: '1:144006347482:ios:1477b85f6c0caed53283e3',
    messagingSenderId: '144006347482',
    projectId: 'werewolf-prm-7717c',
    databaseURL: 'https://werewolf-prm-7717c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'werewolf-prm-7717c.firebasestorage.app',
    iosBundleId: 'com.example.werewolf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA004ZSMMQgZBwpYrWJtID-GJTXL1tcC4A',
    appId: '1:144006347482:web:c5d499297fd3a99d3283e3',
    messagingSenderId: '144006347482',
    projectId: 'werewolf-prm-7717c',
    authDomain: 'werewolf-prm-7717c.firebaseapp.com',
    databaseURL: 'https://werewolf-prm-7717c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'werewolf-prm-7717c.firebasestorage.app',
  );
}
